version: '3.6'

services:
 # 测试服务，探测 traefik 是否能正常转发代理
  whoami:
    image: containous/whoami
    ports:
      - "82:80"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.whoami.rule=PathPrefix(`/whoami`)"
      # 去掉前缀
      - "traefik.http.routers.whoami.middlewares=whoami"
      - "traefik.http.middlewares.whoami.stripprefix.prefixes=/whoami"
    networks:
      - traefik

  flare:
    image: soulteary/flare
    restart: always
    # 默认无需添加任何参数，如有特殊需求
    # 可阅读文档 https://github.com/soulteary/docker-flare/blob/main/docs/advanced-startup.md
    command: flare
      # 启用账号登录模式
      # command: flare --nologin=0
      # environment:
      # 如需开启用户登录模式，需要先设置 `nologin` 启动参数为 `0`
      # 如开启 `nologin`，未设置 FLARE_USER，则默认用户为 `flare`
      # - FLARE_USER=flare
      # 指定你自己的账号密码，如未设置 `FLARE_USER`，则会默认生成密码并展示在应用启动日志中
      # - FLARE_PASS=your_password
    # 是否开启“使用向导”，访问 `/guide`
    # - FLARE_GUIDE=1
    ports:
      - "5005:5005"
    volumes:
      - ./app:/app
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.flare.entrypoints=http"
      - "traefik.http.services.flare.loadbalancer.server.scheme=http"
      - "traefik.http.services.flare.loadbalancer.server.port=5005"
      # assets是图片信息，flare是将请求转发到容器前去掉flare前缀实现的 ||PathPrefix(`/assets`)
      - "traefik.http.routers.flare.rule=PathPrefix(`/flare`) ||PathPrefix(`/assets`) " 
      # 去掉前缀
      - "traefik.http.routers.flare.middlewares=flare"
      - "traefik.http.middlewares.flare.stripprefix.prefixes=/flare"
    networks:
      - traefik

 


networks:
  traefik:
    # 1.网络隔离
    # 2.容器与容器之间也无法相互访问
    # 3.external 参数表示使用 traefik所在的网段，否则都是default网段（但是default网段会变更）
    external: true

