version: '3.3'
services:
  code-server:
    container_name: code-server
    ports:
      - '8080:8080'
    volumes:
      - './.config:/home/coder/.config'
      - './data/codercom:/home/coder/project'
    user: '197108:197121'
    environment:
      - DOCKER_USER=jiahangchun
    image: 'codercom/code-server:latest'