version: '3.3'
services:
  code-server:
    container_name: code-server
    ports:
      - '8080:8080'
    volumes:
      - './.config:/home/coder/.config'
      - './codercom:/home/coder/project'
    user: '1000:1000'
    environment:
      - DOCKER_USER=jiahangchun
    image: 'codercom/code-server:latest'