version: '3.3'
services:
  bind:
    container_name: dns-server
    restart: always
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '10000:10000/tcp'
    volumes:
      - '/e/docker/dns-server:/data'
    image: 'sameersbn/bind:latest'