#docker-compose.yaml
version: '3'

services:
  db:
    image: mysql:5.6
    restart: always
    container_name: "my_mysql"
    environment:
      MYSQL_ROOT_PASSWORD: Hwkj_123456
      MYSQL_DATABASE: webstack
      MYSQL_USER: webstack
      MYSQL_PASSWORD: 123456
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - "webstacknet"
  redis:
    image: redis:3
    container_name: "my_redis"
    restart: always
    networks:
      - "webstacknet"
  webstack:
    image: arvon2014/webstack-laravel:v1.2.1
    container_name: "my_webstack"
    ports:
      - 8000:8000
    depends_on:
      - "db"
      - "redis"
    environment:
      LOGIN_COPTCHA: "false"
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: webstack
      DB_USERNAME: webstack
      DB_PASSWORD: 123456
    command: ['/entrypoint.sh','new-server']
    networks:
      - "webstacknet"
networks:
  webstacknet:
    driver: bridge