version: '3.3'
services:
  bookstack:
    image: linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - DB_PASS=password
      - DB_DATABASE=bookstackapp
      - APP_LANG=zh_CN
      - APP_URL=http://127.0.0.1:6875/
      - WKHTMLTOPDF=/usr/bin/wkhtmltopdf
      # Mail Setting
      - MAIL_DRIVER=smtp
      - MAIL_FROM=jiahangchun@163.com
      - MAIL_FROM_NAME="XXXX知识库"
      # SMTP mail options
      - MAIL_HOST=smtpdm.aliyun.com
      - MAIL_PORT=465
      - MAIL_USERNAME=service@example.com
      - MAIL_PASSWORD=password
      - MAIL_ENCRYPTION=ssl
    volumes:
      - ./data/bookstack:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bookstack.rule=Host(`bookstack.jiahangchun.icu`)"
      - "traefik.http.routers.bookstack.entrypoints=http"
    restart: unless-stopped
    ports:
      - 6875:80
    depends_on:
      - bookstack_db
    networks:
      - traefik
  bookstack_db:
    image: linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=yourdbpass
      - TZ=Asia/Shanghai
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=password
    volumes:
      - ./data/mariadb:/config
    restart: unless-stopped
    networks:
      - traefik

