version: '3.3'
services:
    dns_service:
        container_name: dns-server
        restart: always
        ports:
            - '9001:53/tcp'
            - '9001:53/udp'
            - '10000:10000/tcp'
        volumes:
            - './dns_data:/data'
        image: 'sameersbn/bind:latest'
