version: '2'

networks:
  monitor:
    driver: bridge


services:

  #http://localhost:9100
  node-exporter:
    image: quay.io/prometheus/node-exporter
    container_name: node-exporter
    hostname: node-exporter
    restart: always
    ports:
      - "9100:9100"
    networks:
      - monitor


  # http://localhost:8080/containers/ 查看结果
  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    hostname: cadvisor
    restart: always
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8080:8080"
    networks:
      - monitor


  prometheus:
    image: prom/prometheus
    container_name: prometheus
    hostname: prometheus
    restart: always
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./config/node_down.yml:/etc/prometheus/node_down.yml
    ports:
      - "9090:9090"
    networks:
      - monitor


  #  alertmanager:
  #    image: prom/alertmanager
  #    container_name: alertmanager
  #    hostname: alertmanager
  #    restart: always
  #    volumes:
  #      - ./config/alertmanager.yml:/etc/alertmanager/alertmanager.yml
  #    ports:
  #      - "9093:9093"

  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    environment:
      # 设置默认域名
      #- 'GF_SERVER_ROOT_URL=https://grafana.bladex.vip'
      # 设置admin的密码为cquisse
      - GF_SECURITY_ADMIN_PASSWORD=jiahangchun
    volumes:
      # 一些默认密码之类的配置
      #- './config/grafana.ini:/etc/grafana/grafana.ini'
      - './data/grafana/:/var/lib/grafana'
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - monitor

