version: "3.9"
services:
  ddns-go:
    image: jeessy/ddns-go
    ports: 
      - 9876:9876
    restart: always
    #network_mode: "host"
    volumes:
      - ./data:/root
    labels:
      - "traefik.http.routers.ddns.rule=Host(`ddns.jiahangchun.icu`)"
      - "traefik.http.services.ddns.loadbalancer.server.port=9876"