version: '3.3'

services:
  vaultwarden:
    image: vaultwarden/server:alpine
    container_name: vaultwarden
    restart: always
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 1314:80  # Vaultwarden 映射端口
      - 3012:3012  # Websocket 映射端口
    volumes:
      - /e/docker/vault-data:/data
      # - ./vault-data:/data #可以放在本地执行，也能指定目录
    env_file:
      - ./vault.env  # 环境变量路径