version: '3'

services:
  db:
    image: mariadb
    container_name: chevereto-mysql
    volumes:
      - /e/docker/chevereto/database:/var/lib/mysql:rw
    restart: always
    networks:
      - projectBridge
    environment:
      MYSQL_ROOT_PASSWORD: qwert12345!
      MYSQL_DATABASE: chevereto
      MYSQL_USER: chevereto
      MYSQL_PASSWORD: chevereto

  chevereto:
    depends_on:
      - db
    image: nmtan/chevereto
    restart: always
    networks:
      - projectBridge
    environment:
      CHEVERETO_DB_HOST: db
      CHEVERETO_DB_USERNAME: chevereto
      CHEVERETO_DB_PASSWORD: chevereto
      CHEVERETO_DB_NAME: chevereto
      CHEVERETO_DB_PREFIX: chv_
    volumes:
      - /e/docker/chevereto/chevereto_images:/var/www/html/images:rw
      - ./upload.ini:/usr/local/etc/php/conf.d/upload.ini:ro
    ports:
      - 8880:80

networks:
  projectBridge:
    driver: bridge

