version: '3.3'
services:
    portainer:
        container_name: portainer
        ports:
            - '9000:9000'
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
        restart: always
        image: portainer/portainer

    
# jiahangchun / jiahangchun123